Rjava v0.9 11
conda-forge/r-rjava-feedstock pull request #11
Opened 2019-07-09 22:51 UTC by agcopenhaver

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

2019-07-09 22:51 UTC, agcopenhaver commented
@conda-forge-admin, please rerender

2019-07-09 22:52 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2019-07-10 00:38 UTC, agcopenhaver commented
@conda-forge/r @sodre is this good to go?

2019-07-10 14:29 UTC, jdblischak commented
@agcopenhaver Thanks for working on this!

l'm not qualified to review changes to a build script that involves `R CMD javareconf`. I worry how this will interact with [similar calls in the r-base recipe](https://github.com/conda-forge/r-base-feedstock/search?q=javareconf&unscoped_q=javareconf).

Tagging some folks that would be able to provide a review: @mbargull @isuruf @mingwandroid

2019-07-11 02:45 UTC, sodre requested changes
Minimize white-space changes...

2019-07-11 02:45 UTC, sodre commented on recipe/meta.yaml
> +
```suggestion

```

2019-07-11 02:45 UTC, sodre commented on recipe/meta.yaml
> +
```suggestion

```

2019-07-11 02:45 UTC, sodre commented on recipe/meta.yaml
> +    - openjdk 8.*
```suggestion
    - openjdk 8.*
```

2019-07-11 08:20 UTC, dbast commented
Both r-base scripts contain `R CMD javareconf`:
* https://github.com/conda-forge/r-base-feedstock/blob/master/recipe/activate-r-base.sh
* https://github.com/conda-forge/r-base-feedstock/blob/master/recipe/post-link.sh

Why this is not enough and why adding `R CMD javareconf` also to the build.sh here is fixing the osx build, looks a bit mysterious. But it should be of no harm to have multiple calls of javareconf during build.

2019-07-11 13:53 UTC, agcopenhaver commented on recipe/meta.yaml
> +    - openjdk 8.*
my bad. Don't know why I did that

2019-07-11 13:54 UTC, mbargull commented
My best guess is that this is due to `conda-build`'s environment stacking:
1. (`host` environment's `r-base` post-install script runs `javareconf`)
2. `host` environment gets activated / `host` environment's activation scripts are run \*\*
   1. compiler activation scripts set `CC`, `CFLAGS`, ... with path to relative to `$PREFIX`
         (the compilers are installed into `host` as a dependency of `r-base`)
   2. `r-base` activation script runs `javareconf`
3. `build` environment gets activated / `build` environment's activation scripts are run
   - compiler activation scripts set `CC`, `CFLAGS`, ... with path to relative to `$BUILD_PREFIX`

(\*\* NOTE: Unless this has been fixed in `conda` (didn't check), sadly, the activation scripts are not guaranteed to run in dependency order. AFAIR, they are run in lexicographical order of their filenames. In this case, `activate-{binutils,gcc,...}*.sh` would lexicographically precede `activate-r-base.sh`, so we should get the intended order, thankfully.)

If `javareconf` is influenced by the compiler's environment variables or other path-dependent compiler output, then this would be a likely explanation since `javareconf` is only run in the `host` post-install or activation before `build` gets activated.
=> Running `javareconf` in the build script is likely the right call when there are stacked `host`+`build` environments.

@mingwandroid, @conda-forge/r : I assume this might affects all R packages that compile Java-related things and depend on Java (directly or indirectly through `r-rjava`). Meaning, those packages should likely run `"${PREFIX}/bin/R" CMD javareconf` in their `build.sh`.

NB: I don't use R and macOS. Hence I don't know the peculiarities of R and can't test locally. And I have no idea why only macOS but not Linux failed.

2019-07-11 14:01 UTC, mbargull submitted a review, later dismissed
LGTM, I guess (...says the not fully qualified non-R user)

2019-07-11 20:21 UTC, merged